---
- name: Install required packages for management node
  apt:
    name:
      - ansible
      - python3
      - python3-pip
      - jq
      - git
      - curl
      - vim
      - wget
      - wireguard
    state: present
    update_cache: yes
  become: true

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl
  become: true

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - ~/tfgrid-k3s
    - ~/tfgrid-k3s/infrastructure
    - ~/tfgrid-k3s/platform
    - ~/tfgrid-k3s/scripts
    - ~/.kube

- name: Copy deployment files to management node
  synchronize:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: ~/tfgrid-k3s/
  with_items:
    - infrastructure/
    - platform/
    - scripts/
    - Makefile
    - README.md

- name: Copy kubeconfig to management node
  copy:
    src: "{{ playbook_dir }}/../k3s.yaml"
    dest: ~/.kube/config
    mode: "0600"
  when: lookup('file', playbook_dir + '/../k3s.yaml', errors='ignore') != ""
